package app

const (
	AddrSelectPaso            int = 0
	AddrEnterPaso                 = 1
	AddrEnterRuta                 = 2
	AddrEnterDriver               = 3
	AddrScreenSwitch              = 4
	AddrTogglePopup               = 5
	AddrToggleWarnPopup           = 6
	AddrScreenAlarms              = 7
	AddrScreenProgVeh             = 8
	AddrScreenProgDriver          = 9
	AddrScreenMore                = 10
	AddrLedGsp                    = 12
	AddrLedNetwork                = 11
	AddrEnterService              = 13
	AddrUpdateDropListProgVeh     = 14
	AddrShowSelectProgVeh         = 15
	AddrSelectItinerary           = 16
	AddrExitSwitch                = 17
	AddrShowStep                  = 19
	AddrLedReset                  = 20
	// AddrLedBeep                   = 23
	AddrTextDate           = 60
	AddrTextRoute          = 100
	AddrNumRoute           = 120
	AddrTextDriver         = 140
	AddrNumDriver          = 160
	AddrNumCashInputs      = 84 // 80
	AddrNumElectonicInputs = 80 // 84
	AddrNumDeviation       = 88
	AddrTextCurrentService = 700 //180
	AddrTextCashInputs     = 760
	AddrLedCurrentService  = 200
	// AddrLedSummaryService    = 4160
	AddrLedSummaryService    = 480
	AddrTextCurrentItinerary = 220
	AddrTextWarnPopup        = 300
	AddrTextPopup            = 400
	AddrTextWarning          = 500
	AddrTextConfirmation     = 600
	// AddrSelectProgDriver           = 700
	// AddrSelectProgVeh              = 701
	AddrTextProgDriver         = 1000
	AddrTextProgVeh            = 2000
	AddrResumeSelectProgVeh    = 2600
	AddrItineraryProgVeh       = 2960 // 2994
	AddrItineraryProgVehVerify = 2996
	AddrCurrentSelectProgVeh   = 2998
	AddrTextNotiAlarm          = 3000
	// AddrAddBright              = 21
	AddrSwitchLang1 = 21
	AddrSwitchLang2 = 22
	AddrLedBeep     = 23
	AddrSwitchStep  = 25
	AddrSendStep    = 24

	AddrPrevVehHeaderText  = 4180 // 4100
	AddrCurrVehHeaderText  = 4140
	AddrNextVehHeaderText  = 4100 // 4180
	AddrPrevVehFooterText  = 4300 // 4220
	AddrCurrVehFooterText  = 4260
	AddrNextVehFooterText  = 4220 // 4300
	AddrCurrItineraryText  = 4340
	AddrCurrCheckpointText = 4420
)
