package ui

const (
	ROUTE_TEXT int = iota
	ROUTE_TEXT_READ
	DRIVER_TEXT
	DRIVER_TEXT_READ
	INPUTS_TEXT
	OUTPUTS_TEXT
	DEVIATION_TEXT
	DATE_TEXT
	WARNING_TEXT
	CONFIRMATION_TEXT
	POPUP_TEXT
	POPUP_WARN_TEXT
	PROGRAMATION_VEH_TEXT
	PROGRAMATION_DRIVER_TEXT
	NOTIFICATIONS_ALARM_TEXT
	DOOR_0_LED
	DOOR_1_LED
	DOOR_2_LED
	GPS_LED
	NETWORK_LED
	NOTIFICATIONS_BUTTON
	PROGRAMATION_VEH_BUTTON
	PROGRAMATION_DRIVER_BUTTON
	ADDITIONALS_BUTTON
	SERVICE_CURRENT_STATE
	SERVICE_CURRENT_STATE_TEXT
	RESET
)
